plugins { id 'com.android.application' }
android {
    namespace 'com.lotuzxvan.sampoerna.sandbox'
    compileSdk 36
    defaultConfig {
        applicationId 'com.lotuzxvan.sampoerna.sandbox'
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName '0.2.0'
    }
    buildTypes { release { minifyEnabled false } }
}
dependencies {}
